name: Build QT

on: [push]

jobs:
  build:
    runs-on: windows-latest

    env:
      QTVER: 5.11.2
      vcvars_bat: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"'

    steps:
    - uses: actions/checkout@v1
      with:
        repository: qt/qt5
        ref: v${{ env.QTVER }}
        #submodules: true
        path: QT-Build  # ${{ env.GITHUB_WORKSPACE }}

    - name: Checkout qtbase
      run: |
        git submodule update --init qtbase

    - name: Configure QT
      run: |
        echo "Prepare VS2019 environment..."
        $tempfile = [IO.Path]::GetTempFileName()
        $proc = start-process -NoNewWindow -Wait -PassThru -RedirectStandardOutput $tempfile "$env:ComSpec" "/c $env:vcvars_bat 2> nul && set"
        if ($proc.ExitCode) {exit $proc.ExitCode}
        get-content $tempfile | foreach-object {$n,$v = $_.Split("=",2); set-item -path "env:\$($n)" -value $v}
        del $tempfile

        $deploy_dir = mkdir -Force "$PWD\..\QT\$env:QTVER"
        echo "" "Run QT configure to $deploy_dir..."
        .\configure.bat -prefix $deploy_dir -nomake examples -nomake tests -opensource -confirm-license

    - name: Make QT
      run: |
        echo "Prepare VS2019 environment..."
        $tempfile = [IO.Path]::GetTempFileName()
        $proc = start-process -NoNewWindow -Wait -PassThru -RedirectStandardOutput $tempfile "$env:ComSpec" "/c $env:vcvars_bat 2> nul && set"
        if ($proc.ExitCode) {exit $proc.ExitCode}
        get-content $tempfile | foreach-object {$n,$v = $_.Split("=",2); set-item -path "env:\$($n)" -value $v}
        del $tempfile

        echo "" "Run nmake..."
        nmake

    - name: Install QT
      run: |
        echo "Prepare VS2019 environment..."
        $tempfile = [IO.Path]::GetTempFileName()
        $proc = start-process -NoNewWindow -Wait -PassThru -RedirectStandardOutput $tempfile "$env:ComSpec" "/c $env:vcvars_bat 2> nul && set"
        if ($proc.ExitCode) {exit $proc.ExitCode}
        get-content $tempfile | foreach-object {$n,$v = $_.Split("=",2); set-item -path "env:\$($n)" -value $v}
        del $tempfile

        echo "" "Run nmake install..."
        nmake install

    - uses: actions/upload-artifact@v1
      with:
        name: QT-deploy
        path: ../QT

